---
- name: update_tmux_plugin_perms
  file:
    path: /home/{{username}}/.tmux/plugins
    owner: "{{ username }}"
    group: "{{ username}}"
    recurse: true

- name: update_omz
  file:
    path: /home/{{username}}/.oh-my-zsh
    owner: "{{ username }}"
    group: "{{ username}}"
    recurse: true
