---


- name: Copy hyper config
  tags: hyper-config
  copy:
    src: users/ctimm/.hyper.js
    dest: /home/{{ username }}/
    force: False
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rw,g+r,o--
  


