---
- name: copy zsh p10k dotfile
  tags: powerlevel10k
  copy:
    src: users/ctimm/.p10k.zsh
    dest: /home/{{ username }}/.p10k.zsh
    force: False
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rw,g+r,o--

- name: Copy hyper config
  tags: hyper-config
  copy:
    src: users/ctimm/.hyper.js
    dest: /home/{{ username }}/
    force: False
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: u+rw,g+r,o--
  

- name: users | {{ username }} | clone powerlevel10k repository
  tags: powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /usr/share/zsh-theme-powerlevel10k/
    force: yes
