
- name: users | ctimm | create config directories
  tags: dotfiles,ctimm,tmux,users,zsh
  file:
    path: /home/ctimm/{{ item.dir }}
    state: directory
    owner: ctimm
    group: ctimm
    mode: 0700
  with_items:
    - { dir: ".bash" }
    - { dir: ".config" }
    - { dir: ".config/htop" }
    - { dir: ".tmux" }
    - { dir: ".tmux/config" }
    - { dir: ".tmux/plugins" }
   

- name: users | ctimm | copy tmux config (workstation version)
  tags: dotfiles,users,ctimm,tmux
  copy:
    src: users/ctimm/tmux/tmux.conf.workstation
    dest: /home/ctimm/.tmux.conf
    owner: ctimm
    group: ctimm
    mode: 0600

- name: users | ctimm | copy dotfiles
  tags: dotfiles,users,ctimm,tmux,users,vim,zsh
  copy:
    src: users/ctimm/{{ item.src }}
    dest: /home/ctimm/{{ item.dest }}
    owner: ctimm
    group: ctimm
    mode: 0600
  with_items:
    - { src: "bash/bash_aliases", dest: ".bash/bash_aliases" }
    - { src: "bash/bash_profile", dest: ".bash_profile" }
    - { src: "bash/bash_prompt", dest: ".bash/bash_prompt" }
    - { src: "bash/bash_functions", dest: ".bash/bash_functions" }
    - { src: "bash/bashrc", dest: ".bashrc" }
    - { src: "bash/profile", dest: ".profile" }
    - { src: "git/gitconfig", dest: ".gitconfig" }
    - { src: "htop/htoprc", dest: ".config/htop/htoprc" }
    - { src: "zsh/zshrc", dest: ".zshrc" }
    - { src: "zsh/.p10k.zsh", dest: ".p10k.zsh"}

- name: users | ctimm | clone tmux-completion plugin repository
  tags: dotfiles,ctimm,users,tmux
  git:
    repo: https://github.com/srsudar/tmux-completion.git
    dest: /home/ctimm/.tmux/plugins/completion
    force: yes
  notify: update_tmux_plugin_perms

- name: users | ctimm | clone tmux-continuum plugin repository
  tags: dotfiles,ctimm,users,tmux
  git:
    repo: https://github.com/tmux-plugins/tmux-continuum
    dest: /home/ctimm/.tmux/plugins/continuum
    force: yes
  notify: update_tmux_plugin_perms

- name: users | ctimm | clone tmux-resurrect plugin repository
  tags: dotfiles,ctimm,users,tmux
  git:
    repo: https://github.com/tmux-plugins/tmux-resurrect
    dest: /home/ctimm/.tmux/plugins/resurrect
    force: yes
  notify: update_tmux_plugin_perms

- name: Clone oh-my-zsh
  tags: omz
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: /home/ctimm/.oh-my-zsh
    force: yes
  notify: update_omz

- name: Clone PowerLevel10k
  tags: p10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/ctimm/.oh-my-zsh/custom/themes/powerlevel10k
    force: yes
  notify : update_omz


