- name: software | chromium | install distro package (arch)
  tags: packages,chromium,workstation-packages
  pacman:
    name: chromium
    state: present
  when:
    - ansible_distribution == "Archlinux"
    - chromium is defined
    - chromium == true
