- name: install flameshot
  tags: packages,flameshot,workstation-packages
  pacman:
    name: flameshot
    state: present
    extra_args: sync
    when:
    - ansible_distribution == "Archlinux"
    - flameshot is defined
    - flameshot == true