- name: Install hyper over yay
  tags: hyper
  kewlfft.aur.aur:
    use: yay
    name:
     - hyper
    become_user: ctimm 
  when:
    - ansible_distribution == "Archlinux"
    - hyper is defined
    - hyper == true