- name: software | install workstation distribution packages
  tags: packages,workstation-packages
  package:
    name:
      - "{{ font_fira_mono_package }}"
      - "{{ font_hack_ttf_package }}"
      - "{{ font_inconsolata_package }}"
      - "{{ font_noto_emoji_package }}"
      - "{{ font_terminus_package }}"
      - python-attrs 
      - python-wheel
      - python-pip
      - python-setuptools
      - python-virtualenv
      - tmux
      - htop
      - flatpak

- name: software | snapd
  tags: packages,workstation-packages
  command: yay -S snapd
  when:
    - ansible_distribution == "Archlinux"
    - snap is defined
    - snap == true