- name: software | install workstation distribution packages
  tags: packages,workstation-packages
  package:
    name:
      - go
      - go-tools
      - python-platformdirs
      - python-filelock
      - python-distlib
      - python-virtualenv
      - python-attrs 
      - python-wheel
      - python-pip
      - python-setuptools
      - flatpak
  when: 
   - packages == true

- name: software | snapd
  tags: packages,workstation-packages
  command: yay -S snapd
  when:
    - ansible_distribution == "Archlinux"
    - snap is defined
    - snap == true
  notify: 
    - start-snapd-socket
