dconf_package: dconf

# Fonts
font_fira_mono_package: otf-fira-mono
font_hack_ttf_package: ttf-hack
font_inconsolata_package: ttf-inconsolata
font_noto_emoji_package: noto-fonts-emoji
font_terminus_package: terminus-font
font_hack_nerd-package: ttf-hack-nerd