- name: system setup | utils | install utility packages
  tags: packages,system,settings
  pacman:
    state: present
    name:
      - curl
      - htop
      - neofetch
      - nmap
      - rsync
      - tmux
      - traceroute
      - wget
      - whois
      - "{{ dconf_package }}"
      


