- name: system setup | utils | install utility packages
  tags: packages,system,settings,fonts
  pacman:
    state: present
    name:
      - htop
      - tmux
      - traceroute
      - vim
      - "{{ font_fira_mono_package }}"
      - "{{ font_hack_ttf_package }}"
      - "{{ font_inconsolata_package }}"
      - "{{ font_noto_emoji_package }}"
      - "{{ font_terminus_package }}"
      - "{{ font_hack_nerd_package }}"
  when: ansible_lsb.id == "EndeavourOS"

- name: system setup | utils | install utility packages
  tags: packages,system,settings,fonts
  pacman:
    state: present
    name:
      - nmap
      - tmux
      - traceroute
      - whois
      - vim
      - "{{ font_fira_mono_package }}"
      - "{{ font_hack_nerd_package }}"

  when: ansible_lsb.id == "ManjaroLinux"

