- name: system setup | utils | install utility packages
  tags: packages,system,settings
  pacman:
    state: present
    name:
      - curl
      - htop
      - neofetch
      - nmap
      - rsync
      - tmux
      - traceroute
      - wget
      - whois
      - "{{ dconf_package }}"
      - flatpak
      

- name: Install package_name_1 and package_name_2 using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - otf-nerd-fonts-fira-code 
  when: ansible_lsb.id == "EndeavourOS"



