- name: system setup | utils | install utility packages
  tags: packages,system,settings
  pacman:
    state: present
    name:
      - curl
      - htop
      - neofetch
      - nmap
      - rsync
      - tmux
      - traceroute
      - wget
      - whois
      - "{{ dconf_package }}"
      - flatpak
      - 

- name: system setup | fonts | firacode nf
  tags: yay,fonts
  yay: name=otf-nerd-fonts-fira-code state=present
  when: ansible_lsb.id == "EndeavourOS"



