---
- name: install zsh
  pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: present

- name: install fzf for zsh
  pacman:
    name:
      - fzf
    state: present

- name: change "{{username}}"'s shell to zsh
  become: yes
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh


