---
- name: install zsh
  pacman:
    name:
      - zsh
      - z
      - fzf
      - zsh-autosuggestions
      - zsh-syntax-highlighting
    state: present

- name: change "{{username}}"'s shell to zsh
  become: yes
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh


- name: clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/ctimm/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    force: yes

- name: clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/ctimm/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    force: yes