---
- name: install zsh
  pacman:
    name:
      - zsh
      - z
      - fzf
    state: present

- name: change "{{username}}"'s shell to zsh
  become: yes
  user:
    name: "{{ username }}"
    shell: /usr/bin/zsh


- name: clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: /home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    force: yes

- name: clone zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/{{ username }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    force: yes

- name: users | {{ username }} | clone powerlevel10k repository
  tags: powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /usr/share/zsh-theme-powerlevel10k/
    force: yes