- name: install KDE and KDE apps
  pacman:
    name:
      - plasma-meta
      - kde-applications-meta
      - sddm-kcm
      - clementine
      - audacious
    state: present
    when: install_kde == True

- name: import .kde4 file | Manjaro
  copy:
    src: users/ctimm/{{ item.src }}
    dest: /home/ctimm/{{ item.dest }}
    owner: ctimm
    group: ctimm
    mode: 0600
  with_items:
    - { src: "kdeglobals", dest: ".kde4/share/config/" }
  when: ansible_lsb.id == "ManjaroLinux"