- name: install KDE and KDE apps
  pacman:
    name:
      - plasma-meta
      - kde-applications-meta
      - sddm-kcm
      - clementine
      - audacious
    state: present
    when: install_kde == True

- name: import .kde4 file | Manjaro
  