

- block:
    #Make sure users exist on the system
    - import_tasks: users/{{ username }}.yml
    - import_tasks: users/root.yml

    # Install software
    - import_tasks: software/repositories.yml
    - import_tasks: software/zsh.yml
      # Performing remaining tasks:

      rescue:
        - set_fact: task_failed=true
