# Load distro-specific variables
- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
    - name: get the non root user
      set_fact:
        username: "{{ ansible_user_id }}"
    - import_tasks: users/{{ username }}.yml
    - import_tasks: users/root.yml

    # Install software
    - import_tasks: software/aur.yml
      when: ansible_lsb.id == "ManjaroLinux"
    - import_tasks: software/repositories.yml
    - import_tasks: software/packages_utils.yml
    - import_tasks: software/zsh.yml
      when: ansible_lsb.id == "EndeavourOS"
      
 