---
- name: install zsh
  community.general.pacman:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
    state: present

- name: install fzf for zsh
  community.general.pacman:
    name:
      - fzf
    state: present

- name: change "{{ user_name }}"'s shell to zsh
  become: yes
  user:
    name: "{{ user_name }}"
    shell: /usr/bin/zsh

- name: copy zsh dotfile
  copy:
    src: user_home/.zshrc
    dest: /home/{{ username }}/.zshrc
    force: False
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u+rw,g+r,o--

- name: copy zsh p10k dotfile
  copy:
    src: user_home/.p10k.zsh
    dest: /home/{{ username }}/..p10k.zsh
    force: False
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: u+rw,g+r,o--

- name: clone oh-my-zsh for users
  tags:
    - skip_ansible_lint
  become: yes
  become_user: "{{ user_name }}"
  command: "git clone -c core.autocrlf=input https://github.com/robbyrussel/oh-my-zsh.git .oh-my-zsh"
  args:
    chdir: "~{{ user_name }}"
    creates: "~{{ user_name }}/.oh-my-zsh"

- name: copy powerlevel10k theme
  copy:
    src: zsh-theme-powerlevel10k/
    dest: /usr/share/zsh-theme-powerlevel10k/
    force: False
    mode: u+rw,g+xr,o+x
